# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='availablejobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=200)),
                ('postdate', models.DateField(auto_now_add=True)),
                ('jobdescription', models.TextField(max_length=500)),
            ],
        ),
    ]
